import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyHeader from "./components/myHeader/myHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TalenTrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ marginTop: '8vh' }}>
        <MyHeader />
        {children}
      </body>
    </html>
  );
}
