import type { Metadata } from "next";
import "./globals.css";
import MyHeader from "./components/myHeader/myHeader";
import { Suspense } from "react";
import Loading from "./results/loading";


export const metadata: Metadata = {
  title: "TalenTrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ marginTop: '8vh' }}>
        <MyHeader />
        <Suspense fallback={<Loading />}>

          {children}
        </Suspense>
      </body>
    </html>
  );
}
